### PR TITLE
Textbox

### PR DESCRIPTION
**Pull request by moseschrist**
hi amit, the textbox is complete, please review.

### CODE REVIEW

**Comment by amitresh** [comment]
Asaf,

Very nice progress!

Here is a list of my comments:
Textbox Comments:
1. Why define the same exact position() and resize() members that are already defined in control.h.  You should overload them only if they are different.

2. You accept all kinds of non-ASCII keystrokes as if they are charachters. for example: SHIFT, CTRL, INS etc. All of these are accepted as displayable charachters

3. You should decide on keys that exit the textbox. Like TAB, Enter, etc. Which brings me to the conclusion that we need another InputResult type: Which is, finished_MoveFocus2NextField

4. I did not see you handle cases that are NOT_MINE. Such as a mouse click OUTSIDE the textbox

5. Another question for thought: After entering the LAST charchter of the textbox, the cursor moves one to the right. If there will be a frame around the textbox, it will be on the frame. I think in this case we need to change the cursor shape. Maybe to something more narrow. Not sure what exactly.

**Comment by moseschrist** [comment]
1. you are correct, i'll fix that.
2. yes and no, yes they should i should handle them, no there is no need
for another result, the result here should be "return_to_parent" and the
parent should understand that it should move the focus to another control.
3. I didn't implement most of the desktop things because i want to have a
desktop and then i'll write the code.
4. i'll fix that. do you have any idea of a good cursor shape ? another
possibility is to change the size as stated here:
http://www.cplusplus.com/forum/beginner/120558/

**Comment by amitresh** [comment]
Re' 4: I think the size change is only on the Y-axis. Maybe you can define a full-blinking-cursor and position it on the very last char. Which will mean that at this point hitting the BACKSPC will delete the last character (same as hitting the DEL) -- which will also return the cursor to its regular shape and still positioned on the last character spot. Another BACKSPC will now delete the before-last character.

**Comment by moseschrist** [comment]
maybe we should open issues for this ?

**Comment by amitresh** [comment]
Go ahead ... seems like an interesting issue

**Comment by moseschrist** [comment]
i opened issues everything and resolved them, please verify and close the
issues, if closed i'll merge.

**Pull request closed without merging**
