### PR TITLE
ComboBox review

### PR DESCRIPTION
**Pull request by moseschrist**
please review the ComboBox.

### CODE REVIEW

**Comment by moseschrist** [comment]
pull request confirmed.

**Comment by amitresh** [comment]
regarding #12: 
1. When I click with the mouse on the "V" I expected the drop down to appear -- but nothing happens. I manage the dropdown only when I hit ENTER
2. If I select a short string after I already selected a long one ... the new short string doesn't completely overwrite the field ... chars are left dangling at the end
3. The drop-down menu width (and the area to clear-out and restore) should be as wide as the entire field -- not just as wide as the first label.
4. When the dropbox gets focus, you should make the cursor invisible (like I did in RadioBox and CheckBox) -- then restore it when focus is removed.

**Comment by moseschrist** [comment]
something weird happened. for some reason the ComboBox branch was deleted :/
i commited it again

**Comment by amitresh** [comment]
I resync'ed the ComboBox branch -- but all the problems I mentioned before still exist!

**Pull request closed without merging**
