### PR TITLE
Preliminary Commit of NumericTextBox implementation using the new Con…

### PR DESCRIPTION
**Pull request by amitresh**
…tainers:

The NumericTextBox is-a Container with 3 children: Label + 2 buttons (Up/Down)
In addition it is-a Click-Observer on the 2 buttons. When they are clicked it responds by incremeenting its numeric value.
Also cleaned a few bugs in CheckBox: calculated the total checkBox size in the constructor, rather than the draw()
Cleaned a bug in Decorator, which erroneously implemented the getsize() method as inner->getSize(), which was inccorect.

### CODE REVIEW

**Comment by moseschrist** [comment]
the following need to change:
1. remove the IButton from Numeric Textbox project, it needs to be a project of it's own (it will be used in windows).
2. there is no need to create the classes ButtonUP and Down since they should be an instance of Button.
3. The button should have a vector of listeners of the same kind (clicklisteners) and to all it should send a message that an event had happened (with params stating who is the sender, not the delta) and the listener should behave according to who the sender is (because it should know who it is, regardless of if it's decorated or not, the base class of important controls is statically defined in the implemented containe) that way you can have a generic button which is what we need.

see this simple example:
https://docs.oracle.com/javase/tutorial/displayCode.html?code=https://docs.oracle.com/javase/tutorial/uiswing/examples/events/BeeperProject/src/events/Beeper.java

and here with an example similar to decorating:
https://docs.oracle.com/javase/tutorial/displayCode.html?code=https://docs.oracle.com/javase/tutorial/uiswing/examples/events/MultiListenerProject/src/events/MultiListener.java

**Comment by moseschrist** [comment]
also make the Numeric textbox a private inheritance.
no one should be able to add or remove children from it, it's a container for convenience, not for the customer.

**Comment by amitresh** [comment]
OK. I updated the branch with generic buttons.
In reply to your specific proposals:
1. At the moment I don't think we should complicate the Button beyond providing only a single clickListner. NumericTextBox doesn't need it and neither does a Window. So I suggest to leave it single for the sake of simplicity.

2. If I inherit NumericTB, not PUBLIC, C++ has an issue with casting it to an IControl*. I'm not sure how to get around that. So I left it as-is. Any suggestions?

**Comment by moseschrist** [comment]
since this was not merged yet, i merged the desktop into this branch.

**Comment by amitresh** [comment]
OK. I suggest you merge into Master ... we gotta get moving on completing
this.

On Mon, Feb 29, 2016 at 12:42 PM, moseschrist <notifications@github.com>
wrote:

> since this was not merged yet, i merged the desktop into this branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moseschrist/consoleproject/pull/26#issuecomment-190148488>
> .
>



-- 
-------------------------------
Amit Resh
Software Engineering
*Shenkar*

**Comment by moseschrist** [comment]
you didn't merge it already ?

**Pull request merged**
